SGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('api/', include('apps.api.urls')),
    path('', include('apps.master.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('estados/', include('apps.estados.urls')),
    path('rendiciones/', include('apps.rendiciones.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index ,name='index'),
    path('menu/', views.menu ,name='menu'),
]

apps/rendiciones/urls.py
from django.urls import  path
from . import views

app_name = "rendiciones"

urlpatterns = [
    path('', views.ListaRendiciones.as_view(), name="index"),
    path('crear/', views.CrearRendicion.as_view(), name="crear"),
    path('editar/<int:pk>/', views.EditarRendicion.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy,name='predestroy'),
    path('destroy/<int:pk>',views.destroy,name='destroy'),
    path('obtiene_sitios/<int:pk_cliente>', views.obtiene_sitios, name="obtiene_sitios"),
    path('detalle_rendicion/<int:pk>', views.DetalleRendicion.as_view(), name="detalle_rendicion"),
    path('detalle_rendicion/<int:pk_rendicion>/crear', views.CrearDetalleRendicion.as_view(), name="crear_detalle_rendicion"),
    path('detalle_rendicion/<int:pk_rendicion>/editar/<int:pk>', views.EditarDetalleRendicion.as_view(), name="editar_detalle_rendicion"),
    path('detalle_rendicion/<int:pk_rendicion>/predestroy/<int:pk>',views.predestroy_detalle,name='predestroy_detalle'),
    path('detalle_rendicion/<int:pk_rendicion>/destroy/<int:pk>',views.destroy_detalle,name='destroy_detalle'),
    path('tipo_de_gasto/', views.ListTipoDeGasto.as_view(), name="tipo_de_gasto"),
    path('tipo_de_gasto/crear/', views.CrearTipoDeGasto.as_view(), name="crear_tipo_de_gasto"),
    path('tipo_de_gasto/editar/<int:pk>/', views.EditarTipoDeGasto.as_view(), name="editar_tipo_de_gasto"),
    path('tipo_de_gasto/predestroy/<int:pk>',views.predestroy_tipo_de_gasto,name='predestroy_tipo_de_gasto'),
    path('tipo_de_gasto/destroy/<int:pk>',views.destroy_tipo_de_gasto,name='destroy_tipo_de_gasto'),
]

apps/rendiciones/models.py
from django.db import models
from apps.usuarios.models import Usuario
from apps.clientes.models import Cliente
#Sitios_cliente
from apps.estados.models import Nombre_estado

def file_path(instance, filename):
    return f'{instance.usuario.empresa.nombre}/rendiciones/{filename}'

# Create your models here.
class Rendicion(models.Model):
    descripcion = models.CharField(max_length=100,blank=True,null=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.PROTECT, related_name="rendiciones_usuario")
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT, related_name="rendiciones_cliente")
    encargado = models.CharField(max_length=100,null=True,blank=True)
    estado = models.ForeignKey(Nombre_estado, on_delete=models.PROTECT, related_name="rendiciones_nombre_estado")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id

class TipoDeGasto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=255,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        super(TipoDeGasto, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

def file_path_detalle(instance, filename):
    return f'{instance.rendicion.usuario.empresa.nombre}/rendiciones/{filename}'

class RendicionDetalle(models.Model):
    nombre = models.CharField(max_length=100,blank=True,null=True)
    rendicion = models.ForeignKey(Rendicion, on_delete=models.PROTECT, related_name="rendiciones_detalle_rendicion")
    descripcion = models.TextField()
    sitios_cliente = models.CharField(max_length=255,blank=True,null=True)
    monto = models.CharField(max_length=100,blank=True,null=True)
    documento = models.FileField(upload_to=file_path_detalle,blank=True,null=True)
    kilometraje_inicial = models.CharField(max_length=100,blank=True,null=True)
    kilometraje_final = models.CharField(max_length=100,blank=True,null=True)
    img_km_inicial = models.ImageField(upload_to=file_path_detalle, null=True, blank=True)
    img_km_final = models.ImageField(upload_to=file_path_detalle, null=True, blank=True)
    tipo_gasto = models.ForeignKey(TipoDeGasto, on_delete=models.PROTECT, related_name="rendiciones_detalle_tipo_gasto")
    fecha = models.DateField(blank=True,null=True)
    is_region = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

apps/rendiciones/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.urls import reverse_lazy
from apps.clientes.models import Cliente
#, Sitios_cliente
from apps.estados.models import Nombre_estado
from apps.usuarios.models import Usuario
from .models import *
from .formularios import RendicionDetalleForm, FormularioTipoDeGasto
import datetime, os, json

# Create your views here.
@method_decorator(login_required, name='dispatch')
class ListaRendiciones(ListView):
    model = Rendicion
    template_name = 'rendiciones/rendiciones_list.html'

    def get_context_data(self, **kwargs):
        context = super(ListaRendiciones, self).get_context_data(**kwargs)
        context['appname'] = "rendiciones"
        #from get data set fecha_ini and fecha_fin
        context['fecha_ini'] = self.request.GET.get('fecha_ini')
        context['fecha_fin'] = self.request.GET.get('fecha_fin')
        return context
    
    def get(self, request):
        if self.request.user.has_perm('rendiciones.view_rendiciones'):
            return super().get(request)
        return redirect("master:index")

    def get_queryset(self):
        fecha_ini = self.request.GET.get('fecha_ini')
        fecha_fin = self.request.GET.get('fecha_fin')
        if not fecha_ini or not fecha_fin:
            fecha_ini = datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
            fecha_fin = datetime.datetime.now().replace(hour=23, minute=59, second=59, microsecond=0)        
        queryset = Rendicion.objects.filter(updated_at__range=[fecha_ini, fecha_fin],usuario__empresa=self.request.user.empresa).exclude(estado__nombre="INICIADO")
        return queryset

@method_decorator(login_required, name='dispatch')
class CrearRendicion(CreateView):
    model = Rendicion
    template_name = 'rendiciones/formulario.html'
    fields = ['descripcion', 'usuario', 'cliente', 'encargado', 'estado']

    def get_context_data(self, **kwargs):
        context = super(CrearRendicion, self).get_context_data(**kwargs)
        context['legend'] = "Crear Rendición"
        context['appname'] = "rendiciones"
        context['clientes'] = Cliente.objects.filter(empresa=self.request.user.empresa)
        context['usuarios'] = Usuario.objects.filter(empresa=self.request.user.empresa, is_superuser=False)
        context['estados'] = Nombre_estado.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        if request.user.has_perm('rendiciones.add_rendicion'):
            rendicion = Rendicion()
            rendicion.descripcion = self.request.POST.get('descripcion')
            rendicion.usuario = Usuario.objects.get(id=self.request.POST.get('usuario'))
            rendicion.cliente = Cliente.objects.get(id=self.request.POST.get('cliente'))
            rendicion.encargado = self.request.POST.get('encargado')
            rendicion.estado = Nombre_estado.objects.get(id=self.request.POST.get('estado'))
            rendicion.save()
            messages.success(self.request, 'Rendición creada correctamente')
            return redirect('rendiciones:index')
        return redirect("master:index")

@login_required(login_url="/")
def obtiene_sitios(request, pk_cliente):
    if request.method == "GET":
        if pk_cliente == "0":
            return JsonResponse({"sitios": []})
        try:
            cliente = Cliente.objects.get(pk=pk_cliente)
            # sitios = cliente.sitios_cliente_cliente.all()
            return JsonResponse({"sitios":list(sitios.values())})
        except Cliente.DoesNotExist:
            return JsonResponse({"sitios": []})
    return JsonResponse({"sitios": []})

@method_decorator(login_required, name='dispatch')
class EditarRendicion(UpdateView):
    model = Rendicion
    template_name = 'rendiciones/formulario.html'
    fields = ['descripcion', 'usuario', 'cliente', 'encargado','estado']

    def get_context_data(self, **kwargs):
        context = super(EditarRendicion, self).get_context_data(**kwargs)
        context['legend'] = "Editar Rendición"
        context['appname'] = "rendiciones"
        context['clientes'] = Cliente.objects.filter(empresa=self.request.user.empresa)
        context['usuarios'] = Usuario.objects.filter(empresa=self.request.user.empresa, is_superuser=False)
        context['estados'] = Nombre_estado.objects.all()
        #data for prepopulate form in object
        data = json.dumps({
            'descripcion': self.object.descripcion,
            'usuario': self.object.usuario.id,
            'cliente': self.object.cliente.id,
            'encargado': self.object.encargado,
            'estado': self.object.estado.id,

        })
        context['data'] = data
        return context

    def post(self, request, *args, **kwargs):
        if request.user.has_perm('rendiciones.change_rendicion'):
            rendicion = Rendicion.objects.get(pk=self.kwargs['pk'])
            rendicion.descripcion = self.request.POST.get('descripcion')
            rendicion.usuario = Usuario.objects.get(id=self.request.POST.get('usuario'))
            rendicion.cliente = Cliente.objects.get(id=self.request.POST.get('cliente'))
            rendicion.encargado = self.request.POST.get('encargado')
            rendicion.estado = Nombre_estado.objects.get(id=self.request.POST.get('estado'))
            rendicion.save()
            messages.success(self.request, 'Rendición editada correctamente')
            return redirect('rendiciones:index')
        return redirect("master:index")

@login_required(login_url="/")
def predestroy(request, pk):
    if request.method == "GET":
        try:
            rendicion = Rendicion.objects.get(pk=pk)
        except:
            return redirect("rendiciones:index")
        context={
            'id' : rendicion.id,
            'descripcion': rendicion.descripcion,
            'usuario' : rendicion.usuario.first_name + " " + rendicion.usuario.last_name,
        }
        return JsonResponse(context)
    return redirect("rendiciones:index")

@login_required(login_url="/")
def destroy(request,pk):
    if request.method == "GET":
        if request.user.is_superuser:
            try:
                rendicion = Rendicion.objects.get(pk=pk)
            except:
                return redirect("rendiciones:index")
            if request.user.empresa != rendicion.usuario.empresa:
                return redirect("master:index")
            rendicion.delete()
        else:
            messages.error(request, 'No tiene permisos para eliminar rendiciones')
    return redirect("rendiciones:index")


@method_decorator(login_required, name='dispatch')
class DetalleRendicion(ListView):
    model = RendicionDetalle
    template_name = 'rendiciones/detalle_list.html'
    context_object_name = 'rendicion'
    
    def get(self, request, pk):
        if self.request.user.has_perm('rendiciones.add_rendiciondetalle'):
            return super().get(request)
        return redirect("rendiciones:detalle_rendicion", pk=pk)

    #filter queryset
    def get_queryset(self):
        return RendicionDetalle.objects.filter(rendicion=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(DetalleRendicion, self).get_context_data(**kwargs)
        context['appname'] = "rendiciones_detalle"
        context['pk'] = self.kwargs['pk']
        return context
        
@method_decorator(login_required, name='dispatch')
class CrearDetalleRendicion(CreateView):
    form_class = RendicionDetalleForm
    template_name = 'formularios/generico.html'
    success_url: reverse_lazy('rendiciones:index')

    def get_context_data(self, **kwargs):
        context = super(CrearDetalleRendicion, self).get_context_data(**kwargs)
        context['legend'] = "Crear Detalle de Rendición"
        context['appname'] = "rendiciones"
        context['pk'] = self.kwargs['pk_rendicion']
        return context

    def form_valid(self, form):
        if self.request.user.has_perm('rendiciones.add_rendiciondetalle'):
            form.instance.rendicion = Rendicion.objects.get(pk=self.kwargs['pk_rendicion'])
            form.instance.save()
            messages.success(self.request, 'Detalle de rendición creado correctamente')
            return redirect('rendiciones:detalle_rendicion', pk=self.kwargs['pk_rendicion'])
        return redirect("rendiciones:detalle_rendicion", pk=self.kwargs['pk_rendicion'])


@method_decorator(login_required, name='dispatch')
class EditarDetalleRendicion(UpdateView):
    template_name = 'formularios/generico.html'
    model = RendicionDetalle
    form_class = RendicionDetalleForm

    def get_context_data(self, **kwargs):
        context = super(EditarDetalleRendicion, self).get_context_data(**kwargs)
        context['legend'] = "Editar Detalle de Rendición"
        context['appname'] = "rendiciones"
        return context

    def form_valid(self, form):
        form.save()
        return redirect("rendiciones:detalle_rendicion", pk=self.kwargs['pk_rendicion'])

@login_required(login_url="/")
def predestroy_detalle(request, pk_rendicion, pk):
    if request.method == "GET":
        try:
            detalle = RendicionDetalle.objects.get(pk=pk)
        except:
            return redirect("rendiciones:index")
        context={
            'rendicion_id' : pk_rendicion,
            'id' : detalle.id,
            'nombre': detalle.nombre,
            'descripcion': detalle.descripcion,
        }
        return JsonResponse(context)
    return redirect("rendiciones:detalle_rendicion", pk=pk_rendicion)

@login_required(login_url="/")
def destroy_detalle(request,pk_rendicion,pk):
    if request.method == "GET":
        if request.user.is_superuser:
            try:

templates/rendiciones/detalle_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'rendiciones:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver Atrás</a>
    <div>
        <a href="{% url 'rendiciones:crear_detalle_rendicion' pk_rendicion=pk %}"
            class="btn btn-success text-light border border-custom me-2"><i class="fas fa-plus-circle"></i> Agregar
            Detalle</a>
    </div>
</div>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Monto Neto</th>
                <th>Monto IVA</th>
                <th>Fecha creación</th>
                <th>Fecha modificación</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for detalle in object_list %}
            <tr>
                <td>{{detalle.id}}</td>
                <td>{{detalle.nombre}}</td>
                <td>{{detalle.monto_neto}}</td>
                <td>{{detalle.monto_iva}}</td>
                <td>{{detalle.created_at|date:"Y/m/d H:i:s"}}</td>
                <td>{{detalle.updated_at|date:"Y/m/d H:i:s"}}</td>
                <td style="vertical-align: middle;">
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'rendiciones:editar_detalle_rendicion' pk_rendicion=pk pk=detalle.id %}"
                        id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal"
                        data-popup-url="{% url 'rendiciones:predestroy_detalle' pk_rendicion=pk pk=detalle.id %}"
                        href=""><i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar el siguiente detalle de
                    rendición?:
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $(".dataTable").on('click', '.open-modal', function () {
            $.ajax({
                type: "GET",
                url: $(this).attr("data-popup-url"),
                dataType: "json",
                success: function (data) {
                    Datos =
                        "<p notempty='not'> Nombre: " + data['nombre'] +
                        "</p><p notempty='not'> Descripción: " + data['descripcion'] +
                        "</p>";
                    $(".modal-body").append(Datos);
                    $("#delete").click(function () {
                        window.location.href = "/rendiciones/detalle_rendicion/" +
                            data["rendicion_id"] + "/destroy/" + data["id"];
                    })
                }
            });
        });
        $("#close").on("click", function () {
            $(".modal-body").empty();
        })

        $('body').click(function (e) {
            if ($(e.target).attr('notempty') != "not")
                $(".modal-body").empty();
        });
    });
</script>
{% endblock javascript %}

templates/rendiciones/rendiciones_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    <div>
        <a href="{% url 'rendiciones:crear' %}" class="btn btn-success text-light border border-custom me-2"><i
                class="fas fa-plus-circle"></i> Agregar Rendición</a>
    </div>
    <form action="{% url 'rendiciones:index' %}" method="GET" class="form-inline">
        <div class="form-group mx-sm-3 mb-2">
            <label for="fecha_ini" class="me-1">Fecha Inicio: </label>
            <input type="datetime-local" class="form-control" id="fecha_ini" name="fecha_ini"
                placeholder="Fecha Inicio">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label for="fecha_fin" class="me-1">Fecha Fin: </label>
            <input type="datetime-local" class="form-control" id="fecha_fin" name="fecha_fin" placeholder="Fecha Fin">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Buscar</button>
    </form>
</div>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Usuario</th>
                <th>Cliente</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>Fecha creación</th>
                <th>Fecha modificación</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for rendicion in object_list %}
            <tr>
                <td style="vertical-align: middle;">{{rendicion.id}}</td>
                <td style="vertical-align: middle;">{{rendicion.usuario.first_name}} {{rendicion.usuario.last_name}}
                </td>
                <td style="vertical-align: middle;">{{rendicion.cliente}}</td>
                <td style="vertical-align: middle;">{{rendicion.descripcion}}</td>
                <td style="vertical-align: middle;">{{rendicion.estado.nombre}}</td>
                <td style="vertical-align: middle;">{{rendicion.created_at|date:"Y/m/d H:i:s"}}</td>
                <td style="vertical-align: middle;">{{rendicion.updated_at|date:"Y/m/d H:i:s"}}</td>
                <td style="vertical-align: middle;">
                    <a href="{% url 'rendiciones:detalle_rendicion' pk=rendicion.id %}"
                        class="btn btn-warning text-light border border-custom me-2"><i class="fas fa-edit"></i>
                        Detalles</a>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'rendiciones:editar' pk=rendicion.id %}" id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal" data-popup-url="{% url 'rendiciones:predestroy' pk=rendicion.id %}"
                        href=""><i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar la siguiente rendición?:
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $(".dataTable").on('click', '.open-modal', function () {
            $.ajax({
                type: "GET",
                url: $(this).attr("data-popup-url"),
                dataType: "json",
                success: function (data) {
                    Datos =
                        "<p notempty='not'> Nombre Usuario: " + data['usuario'] +
                        "</p><p notempty='not'> Descripción: " + data['descripcion'] +
                        "</p>";
                    $(".modal-body").append(Datos);
                    $("#delete").click(function () {
                        window.location.href = "/rendiciones/destroy/" +
                            data["id"];
                    })
                }
            });
        });
        $("#close").on("click", function () {
            $(".modal-body").empty();
        })

        $('body').click(function (e) {
            if ($(e.target).attr('notempty') != "not")
                $(".modal-body").empty();
        });
    });

    // if fecha_ini from request.get form set value to input else set value to today date at 00:00
    if ('{{fecha_ini}}' != 'None' && '{{fecha_ini}}' != '') {
        $('#fecha_ini').val('{{fecha_ini}}');
    } else {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var yyyy = today.getFullYear();

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd + 'T00:00';
        $('#fecha_ini').val(today);
    }
    //if fecha_fin from request.get form set value to input else set value to today date at 00:00
    if ('{{fecha_fin}}' != 'None' && '{{fecha_fin}}' != '') {
        $('#fecha_fin').val('{{fecha_fin}}');
    } else {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var yyyy = today.getFullYear();

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd + 'T23:59';
        $('#fecha_fin').val(today);
    }
</script>
{% endblock javascript %}