SGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('api/', include('apps.api.urls')),
    path('', include('apps.master.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('estados/', include('apps.estados.urls')),
    path('rendiciones/', include('apps.rendiciones.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clientes/urls.py
from django.urls import  path
from . import views

app_name = "clientes"

urlpatterns = [
    path('', views.ListaClientes.as_view(), name="index"),
    path('crear', views.CrearClientes.as_view(), name="crear"),
    path('editar/<int:pk>', views.EditarCliente.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    # path('sitios/<int:pk>', views.ListaSitiosCliente.as_view(), name="sitios"),
    # path('sitios/crear/<int:pk>', views.CrearSitiosCliente.as_view(), name="sitios_crear"),
    # path('sitios/editar/<int:pk>', views.EditarSitioCliente.as_view(), name="sitios_editar"),
    # path('sitios/predestroy/<int:pk>/<int:pk_cliente>',views.predestroy_sitio, name="predestroy_sitio"),
    # path('sitios/destroy/<int:pk>/<int:pk_cliente>',views.destroy_sitio, name="destroy_sitio"),
]

apps/empresas/urls.py
from django.urls import  path
from . import views

app_name = "empresas"

urlpatterns = [
    path('', views.ListEmpresas.as_view(), name="index"),
    path('crear', views.CrearEmpresa.as_view(), name="crear"),
    path('editar/<int:pk>', views.EditEmpresa.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    # path('cargaLogo/<int:pk>',views.CargaLogo, name="cargaLogo"),
    path('cambiar-empresa/<int:pk>',views.cambiarEmpresa, name="cambiarEmpresa"),
]

apps/estados/urls.py
from django.urls import  path
from . import views

app_name = "estados"

urlpatterns = [
    path('', views.ListaEstados.as_view(), name="index"),
]

apps/usuarios/urls.py
from django.urls import  path
from .formularios import UserLoginForm
from . import views

app_name = "usuarios"

urlpatterns = [
    path('',views.ListUsuarios.as_view(), name='index'),
    path('registrar', views.Registrar.as_view(), name="registrar"),
    path('login',views.Login.as_view(authentication_form=UserLoginForm),name='login'),
    path('perfil/<int:pk>',views.Profile.as_view(),name='perfil'),
    path('crear',views.CreateUsuario.as_view(),name='crear'),
    path('editar/<int:pk>',views.EditUsuario.as_view(),name='editar'),
    path('predestroy/<int:pk>',views.predestroy,name='predestroy'),
    path('destroy/<int:pk>',views.destroy,name='destroy'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" class="">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'master/vendor/bootstrap-5.1.3-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'master/vendor/bootstrap-5.1.3-dist/css/sb-admin-2.css' %}">
    <link rel="stylesheet" href="{% static 'master/vendor/fontawesome-free-5.15.4-web/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'master/vendor/DataTables/datatables.min.css'%} " />
    <link rel="stylesheet"
        href="{% static 'master/vendor/DataTables/ColReorder-1.5.4/css/colReorder.dataTables.min.css'%}" />
    <link rel="stylesheet"
        href="{% static 'master/vendor/DataTables/Responsive-2.2.9/css/responsive.dataTables.min.css'%} " />
    <link rel="stylesheet"
        href="{% static 'master/vendor/DataTables/Buttons-2.0.1/css/buttons.dataTables.min.css'%} " />

    <!-- Fin  -->
    <!-- Icono Navegador -->
    <link rel="shortcut icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <!-- Fin  -->
    <!-- Fin Icono Navegador -->
    <link rel="stylesheet" href="{% static 'master/css/style.css' %}">
    <link rel="stylesheet" href="{% block styles %}{% endblock styles %}">
    <!-- Fin  -->
    <title class="edit_appname">SGG | {{appname|capfirst}}</title>
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- sidebar -->
        {% include "sidebar.html" %}
        <!-- End sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include "topbar.html" %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block contenido %}{% endblock contenido %}
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <a href="https://www.telectronic.com"
                            class="mb-3 ms-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                            <span class="text-muted">Copyright &copy; 2022 Telectronic</span>
                        </a>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <script src="{% static 'master/vendor/jquery/jquery-3.6.0.js'  %}"></script>
    <script src="{% static 'master/vendor/jquery/jquery.mask.min.js'  %}"></script>
    <script src="{% static 'master/vendor/bootstrap-5.1.3-dist/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'master/vendor/bootstrap-5.1.3-dist/js/sb-admin-2.js' %}"></script>
    <script src="{% static 'master/vendor/bootstrap-5.1.3-dist/js/bootstrap-show-password.min.js'  %}"></script>
    <script src="{% static 'master/vendor/fontawesome-free-5.15.4-web/js/all.js'  %}"></script>

    <script src="{% static 'master/vendor/jQWidgets/jqxcore.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/jqxchart.core.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/jqxdraw.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/jqxdata.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/jqxdatetimeinput.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/jqxcalendar.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/jqxtooltip.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/globalization/globalize.js' %}"></script>
    <script src="{% static 'master/vendor/jQWidgets/globalization/globalize.culture.es.js' %}"></script>
    <script src="{% static 'master/vendor/jqwidgets/jqxslider.js' %}"></script>
    <script src="{% static 'master/vendor/jqwidgets/jqxbuttons.js' %}"></script>
    <script src="{% static 'master/vendor/jqwidgets/jqxlistbox.js' %}"></script>
    <script src="{% static 'master/vendor/jqwidgets/jqxscrollbar.js' %}"></script>
    <script src="{% static 'master/vendor/jqwidgets/jqxdropdownlist.js' %}"></script>

    <script src="{% static 'master/vendor/DataTables/datatables.min.js'%}"></script>

    <!-- Begin of Responsive DataTable -->
    <script src="{% static 'master/vendor/DataTables/ColReorder-1.5.4/js/dataTables.colReorder.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/Responsive-2.2.9/js/dataTables.responsive.min.js'%}"></script>
    <!-- End of Responsive DataTable -->

    <!-- Begin of Buttons DataTable -->
    <script src="{% static 'master/vendor/DataTables/Buttons-2.0.1/js/dataTables.buttons.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/JSZip-2.5.0/jszip.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/pdfmake-0.1.36/pdfmake.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/pdfmake-0.1.36/vfs_fonts.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/Buttons-2.0.1/js/buttons.html5.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/Buttons-2.0.1/js/buttons.print.min.js'%}"></script>
    <!-- End of Buttons DataTable -->

    <script src="{% static 'master/vendor/jquery-easing/jquery.easing.min.js'  %}"></script>

    <script>
        $("#nav-{{appname}}").parent().parent().addClass('show');
        $("#nav-{{appname}}").addClass("active")
        var printCounter = 0;
        $('#tabla_base').DataTable({
            rowReorder: {
                selector: 'td:nth-child(2)'
            },
            responsive: true,
            "language": {
                "url": "{% static 'master/vendor/DataTables/Spanish.json'%}",
            },
            dom: 'lBfrtip',
            buttons: [
                'copy',
                {
                    extend: 'excel',
                    title: '{{appname}}',
                    messageTop: null
                },
                {
                    extend: 'pdf',
                    title: '{{appname}}',
                    messageBottom: null
                },
                {
                    extend: 'print',
                    title: '{{appname}}',

                    messageTop: function () {
                        printCounter++;

                        if (printCounter === 1) {
                            return 'Esta es la primera vez que imprime este documento.';
                        } else {
                            return 'Has impreso este documento ' + printCounter + ' Veces';
                        }
                    },
                    messageBottom: null
                }
            ],
        });


        $('.edit_appname').text(function (index, text) {
            return text.replace(/_/g, ' ');
        });

        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
    {% block javascript %}
    {% endblock javascript%}
</body>

</html>

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="row">
    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_ingresadas">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">CANTIDAD USUARIOS</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            {{usuarios}}
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users-cog fa-2x text-gray-300"></i>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_contestadas">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">CANTIDAD </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            {{anexos}}
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-phone fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_abandonadas">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary  mb-1">CANTIDAD </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            {{agentes}}
                        </div>
                    </div>
                    <div class="col-auto">

                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4" id="llamadas_outbound">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary  mb-1">CANTIDAD
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            {{colas}}

                        </div>
                    </div>
                    <div class="col-auto">

                        <i class="far fa-bookmark fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-6 col-lg-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Memoria RAM</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div id='chartmemoriaram' style="width: 100%; height: 180px;"></div>
            </div>
        </div>
    </div>

    <div class="col-xl-6 col-lg-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">HDD</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div id="charthdd" style="width: 100%; height: 180px;"></div>
            </div>
        </div>
    </div>

</div>
{% endblock contenido %}
{% block javascript %}

<script>
    var data = [{
            valor: "{{ramUsage}}",
            nombre: "Usado"
        },
        {
            valor: "{{ramAvailable}}",
            nombre: "Restante"
        }
    ];

    $(document).ready(function () {

        var dataAdapter = new $.jqx.dataAdapter(data, {
            async: false,
            autoBind: true,
            loadError: function (xhr, status, error) {
                alert('Error loading "' + source.url + '" : ' + error);
            }
        });
        $.jqx._jqxChart.prototype.colorSchemes.push({
            name: 'myScheme',
            colors: ['#FF5733', '#2980B9']
        });
        // prepare jqxChart settings
        var settings = {
            title: "",
            description: "",
            enableAnimations: true,
            showLegend: true,
            showBorderLine: true,
            legendLayout: {
                left: 050,
                top: 100,
                width: 100,
                height: 80,
                flow: 'vertical'
            },
            padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            titlePadding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            source: dataAdapter,
            colorScheme: 'myScheme',
            seriesGroups: [{
                type: 'pie',
                showLabels: true,
                series: [{
                    dataField: 'valor',
                    displayText: 'nombre',
                    labelRadius: 100,
                    initialAngle: 10,
                    radius: 80,
                    centerOffset: 0,
                    formatFunction: function (value) {
                        if (isNaN(value))
                            return value;
                        return parseInt(value) + '%';
                    },
                }]
            }]
        };
        // setup the chart
        $('#chartmemoriaram').jqxChart(settings);
    });




    var data2 = [{
            valor: "{{hddUsage}}",
            nombre: "Usado"
        },
        {
            valor: "{{hddAvailable}}",
            nombre: "Restante"
        }

    ];
    $(document).ready(function () {

        var dataAdapter = new $.jqx.dataAdapter(data2, {
            async: false,
            autoBind: true,
            loadError: function (xhr, status, error) {
                alert('Error loading "' + source.url + '" : ' + error);
            }
        });
        $.jqx._jqxChart.prototype.colorSchemes.push({
            name: 'myScheme2',
            colors: ['#FF5733', '#2980B9']
        });
        // prepare jqxChart settings
        var settings2 = {
            title: "",
            description: "",
            enableAnimations: true,
            showLegend: true,
            showBorderLine: true,
            legendLayout: {
                left: 050,
                top: 100,
                width: 100,
                height: 80,
                flow: 'vertical'
            },
            padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            titlePadding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0
            },
            source: dataAdapter,
            colorScheme: 'myScheme2',
            seriesGroups: [{
                type: 'pie',
                showLabels: true,
                series: [{
                    dataField: 'valor',
                    displayText: 'nombre',
                    labelRadius: 100,
                    initialAngle: 10,
                    radius: 80,
                    centerOffset: 0,
                    formatFunction: function (value) {
                        if (isNaN(value))
                            return value;
                        return parseFloat(value) + 'G';
                    },
                }]
            }]
        };
        // setup the chart
        $('#charthdd').jqxChart(settings2);
    });


    $(document).ready(function () {

        var data = [];
        var max = 100;
        var timestamp = new Date();
        for (var i = 0; i < 60; i++) {
            timestamp.setMilliseconds(0);
            timestamp.setSeconds(timestamp.getSeconds() - 1);
            data.push({
                timestamp: new Date(timestamp.valueOf()),
                value: Math.max(100, (Math.random() * 1000) % max)
            });
        }
        data = data.reverse();
    });
</script>

{% endblock javascript %}

templates/sidebar.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-sidebar sidebar sidebar-dark accordion fs-3 text" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center m-1" href="/">
        <div class="sidebar-brand-icon ">
            <h2>SIS<span>RG</span></h2>
        </div>

    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li id="nav-dashboard" class="nav-item ">
        <a class="nav-link" href="/">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        General
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    {% if user.is_superuser  %}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-bs-toggle="collapse"
            data-bs-target="#collapseSA" aria-expanded="false" aria-controls="collapseSA">
            <i class="fas fa-brain"></i>
            <span>Super-Admin</span>
        </a>
        <div id="collapseSA" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionSidebar">
            <div class="bg-white py-2 font-weight-bold collapse-inner rounded">
                <a id="nav-usuarios" class="collapse-item font-weight-bold" href="{% url 'usuarios:index' %}">Usuarios
                    Admin</a>
                <a id="nav-empresas" class="collapse-item font-weight-bold"
                    href="{% url 'empresas:index' %}">Empresas</a>
                <a id="nav-estados" class="collapse-item font-weight-bold" href="{% url 'estados:index' %}">Estados</a>
            </div>
        </div>
    </li>
    {% endif %}


    <!-- Nav Item - Utilities Collapse Menu -->
    {% if user.is_staff  %}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-bs-toggle="collapse"
            data-bs-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilidades</span>
        </a>
        <div id="collapseUtilities" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a id="nav-clientes" class="collapse-item font-weight-bold"
                    href="{% url 'clientes:index' %}">Clientes</a>
                <a id="nav-tipo_de_gasto" class="collapse-item font-weight-bold"
                    href="{% url 'rendiciones:tipo_de_gasto' %}">Tipos de Gastos</a>
            </div>
        </div>
    </li>
    <hr class="sidebar-divider d-none d-md-block mb-0">

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-bs-toggle="collapse"
            data-bs-target="#collapserendiciones" aria-expanded="true" aria-controls="collapserendiciones">
            <i class="fas fa-address-book"></i>
            <span>Rendiciones</span>
        </a>
        <div id="collapserendiciones" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a id="nav-rendiciones" class="collapse-item font-weight-bold"
                    href="{% url 'rendiciones:index' %}">Detalles</a>
            </div>

        </div>
    </li>
    {% endif %}

    <hr class="sidebar-divider d-none d-md-block">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
{% block javascript %}

{% endblock javascript %}

templates/topbar.html
{% load static %}
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <div class="d-sm-flex align-items-center justify-content-between ">
        <h1 id="edit_appname" class="h4 mb-0 text-danger edit_appname">{{appname|upper}}</h1>
    </div>
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - User Information -->

        <li class="nav-item dropdown no-arrow">
            <a class="nav-link disabled text-dark">{{user.empresa.nombre}}</a>
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle  " href="#" id="navbarDropdownMenuLink" role="button"
                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Bienvenido {{user.first_name}}</span>
                <img class="img-profile rounded-circle" src="{% static 'master/img/logo_tlc.png' %}">
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'usuarios:perfil' pk=user.id %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Cerrar Sesión
                </a>
            </div>
        </li>
    </ul>
</nav>

<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Confirma?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body-logout ms-4 p-3">Estás seguro que quieres finalizar sesión?.</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <a class="btn btn-danger" href="{% url 'logout' %}">Salir</a>
            </div>
        </div>
    </div>
</div>