SGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('api/', include('apps.api.urls')),
    path('', include('apps.master.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('estados/', include('apps.estados.urls')),
    path('rendiciones/', include('apps.rendiciones.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/empresas/urls.py
from django.urls import  path
from . import views

app_name = "empresas"

urlpatterns = [
    path('', views.ListEmpresas.as_view(), name="index"),
    path('crear', views.CrearEmpresa.as_view(), name="crear"),
    path('editar/<int:pk>', views.EditEmpresa.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    # path('cargaLogo/<int:pk>',views.CargaLogo, name="cargaLogo"),
    path('cambiar-empresa/<int:pk>',views.cambiarEmpresa, name="cambiarEmpresa"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index ,name='index'),
    path('menu/', views.menu ,name='menu'),
]

apps/empresas/models.py
from django.db import models

# Create your models here.
class Empresa(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    logo = models.TextField(default="/static/master/img/logo.png")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.nombre

apps/empresas/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib import messages
from apps.usuarios.models import Usuario
from .models import Empresa
from .formularios import FormularioEmpresa
import os
# Create your views here.

@method_decorator(login_required, name='dispatch')
class ListEmpresas(ListView):
    model = Empresa
    template_name = "empresas/empresas_list.html"

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        return redirect("master:index")

    def get_context_data(self, **kwargs):
        context = super(ListEmpresas, self).get_context_data(**kwargs)
        context['appname'] = "empresas" 
        return context

class CrearEmpresa(CreateView):
    template_name = "empresas/formulario.html"
    form_class = FormularioEmpresa
    success_url = reverse_lazy("empresas:index")

    def get_context_data(self, **kwargs):
        context = super(CrearEmpresa, self).get_context_data(**kwargs)
        context['legend'] = "Registro empresa"
        context['appname'] = "empresas"
        return context

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser or Empresa.objects.count() == 0:
            return super().get(*args, **kwargs)
        return redirect("master:index")

    def form_valid(self,form):
        empresa = form.save()
        if not os.path.exists(f"media/{empresa.nombre}"):
            os.mkdir("media/"+empresa.nombre)
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class EditEmpresa(UpdateView):
    template_name = "empresas/formulario.html"
    model = Empresa
    form_class = FormularioEmpresa
    success_url = reverse_lazy("empresas:index")

    def get_context_data(self, **kwargs):
        context = super(EditEmpresa, self).get_context_data(**kwargs)
        context['legend'] = "Editar Empresa"
        context['appname'] = "empresas"
        return context
        
    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        return redirect("master:index")

@login_required(login_url="/")
def predestroy(request, pk):
    if request.method == "GET":
        try:
            empresa = Empresa.objects.get(id=pk)
        except:
            return redirect("empresas:index")
        context={
            'id' : empresa.id,
            'nombre': empresa.nombre,
        }
        return JsonResponse(context)
    return redirect("empresas:index")

@login_required(login_url="/")
def destroy(request,pk):
    if request.method == "GET":
        if request.user.is_superuser:
            try:
                empresa = Empresa.objects.get(id=pk)
            except:
                return redirect("empresas:index")
            try:
                empresa.delete()
                #remove media folder
                if os.path.exists(f"media/{empresa.nombre}"):
                    os.rmdir("media/"+empresa.nombre)
            except:
                messages.success(request,f'No se puede eliminar empresa ya que tiene elementos asignados',extra_tags='danger')
                return redirect("empresas:index")
    return redirect("empresas:index")

@login_required(login_url="/")
def cambiarEmpresa(request, pk):
    if request.method == "GET":
        if request.user.is_superuser:
            empresa = Empresa.objects.get(id=pk)
            usuario = Usuario.objects.get(id=request.user.id)
            usuario.empresa = empresa
            usuario.save()
    return redirect("empresas:index")

templates/empresas/empresas_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    <a href="{% url 'empresas:crear' %}" class="align-self-center ms-2 mb-1 btn btn-success text-light border"><i
            class="fas fa-plus-circle"></i> Agregar Empresa</a>
</div>
<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for empresa in object_list %}
            <tr>
                <td>{{empresa.id}}</td>
                <td>{{empresa.nombre}}</td>
                <td>
                    <a class="btn btn-dark btn-sm text-light border border-dark m-1"
                        href="{% url 'empresas:cambiarEmpresa' pk=empresa.id %}" id="view"><i class="fas fa-eye"></i>
                        Administrar</a>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'empresas:editar' pk=empresa.id %}" id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal" data-popup-url="{% url 'empresas:predestroy' pk=empresa.id %}" href="">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar la siguiente
                    Empresa?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}
{% block javascript %}
<script>
    $(".dataTable").on('click', '.open-modal', function () {
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                Datos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " + data['nombre'] +
                    "</p>";
                $(".modal-body").append(Datos);
                $("#delete").click(function () {
                    window.location.href = "/empresas/destroy/" + data["id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}

templates/empresas/formulario.html
{% extends user.is_authenticated|yesno:"base.html,registration/base_login.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

{% if user.is_authenticated %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <button onclick="history.back()" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Atrás</button>
</div>
<div class="col-8 p-3 mx-auto border border-primary">
    <form enctype="multipart/form-data" class="text-dark" method="POST" class="rounded-3 text-white">
        {% else %}
        <form enctype="multipart/form-data" method="POST" class="rounded-3 text-white">
            {% endif %}
            <h2 class="text-center">{{legend}}</h2>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            {% crispy form %}
        </form>
</div>

{% endblock contenido %}