SGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('api/', include('apps.api.urls')),
    path('', include('apps.master.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('estados/', include('apps.estados.urls')),
    path('rendiciones/', include('apps.rendiciones.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clientes/urls.py
from django.urls import  path
from . import views

app_name = "clientes"

urlpatterns = [
    path('', views.ListaClientes.as_view(), name="index"),
    path('crear', views.CrearClientes.as_view(), name="crear"),
    path('editar/<int:pk>', views.EditarCliente.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    # path('sitios/<int:pk>', views.ListaSitiosCliente.as_view(), name="sitios"),
    # path('sitios/crear/<int:pk>', views.CrearSitiosCliente.as_view(), name="sitios_crear"),
    # path('sitios/editar/<int:pk>', views.EditarSitioCliente.as_view(), name="sitios_editar"),
    # path('sitios/predestroy/<int:pk>/<int:pk_cliente>',views.predestroy_sitio, name="predestroy_sitio"),
    # path('sitios/destroy/<int:pk>/<int:pk_cliente>',views.destroy_sitio, name="destroy_sitio"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index ,name='index'),
    path('menu/', views.menu ,name='menu'),
]

apps/clientes/models.py
from django.db import models
from apps.empresas.models import Empresa

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    direccion = models.CharField(max_length=100, blank=True, null=True)
    telefono = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    logo = models.TextField(default="",blank=True,null=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name='clientes_empresa')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__ (self):
        return self.nombre

# class Sitios_cliente(models.Model):
#     cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='sitios_cliente_cliente')
#     nombre = models.CharField(max_length=100, unique=True)
#     direccion = models.CharField(max_length=100, blank=True, null=True)
#     telefono = models.CharField(max_length=100, blank=True, null=True)
#     email = models.EmailField(blank=True, null=True)
#     encargado = models.CharField(max_length=100, blank=True, null=True)
#     empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name='clientes_sitios_empresa')
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
    
#     def __str__ (self):
#         return self.nombre

apps/clientes/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Cliente
#, Sitios_cliente
from .formularios import FormularioCliente
#, FormularioSitioCliente

# Create your views here.
@method_decorator(login_required, name='dispatch')
class ListaClientes(ListView):
    model = Cliente
    template_name = 'clientes/clientes_list.html'

    def get_context_data(self, **kwargs):
        context = super(ListaClientes, self).get_context_data(**kwargs)
        context['appname'] = "clientes"
        return context

    def get_queryset(self):
        queryset = Cliente.objects.filter(empresa=self.request.user.empresa)
        return queryset
    
    def get(self, request):
        if self.request.user.has_perm('clientes.view_clientes'):
            return super().get(request)
        return redirect("master:index")

@method_decorator(login_required, name='dispatch')
class CrearClientes(CreateView):
    template_name = "clientes/formulario.html"
    form_class = FormularioCliente
    success_url = reverse_lazy("clientes:index")

    def form_valid(self, form):
        ruta = form.save(commit = False)
        ruta.empresa = self.request.user.empresa
        ruta.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CrearClientes, self).get_context_data(**kwargs)
        context['legend'] = "Agregar Cliente"
        context['appname'] = "clientes"
        return context

    def get(self, request):
        if self.request.user.has_perm('clientes.add_clientes'):
            return super().get(request)
        return redirect("master:index")

@method_decorator(login_required, name='dispatch')
class EditarCliente(UpdateView):
    template_name = "clientes/formulario.html"
    model = Cliente
    form_class = FormularioCliente
    success_url = reverse_lazy("clientes:index")

    def get_context_data(self, **kwargs):
        context = super(EditarCliente, self).get_context_data(**kwargs)
        context['legend'] = "Editar Cliente"
        context['appname'] = "clientes"
        return context

    def get(self, request, pk):
        objeto = self.get_object()
        if self.request.user.empresa != objeto.empresa:
            return redirect("master:index")
        elif not self.request.user.has_perm('clientes.change_clientes'):
            return redirect("clientes:index")
        return super().get(request)

@login_required(login_url="/")
def predestroy(request, pk):
    if request.user.has_perm('clientes.delete_clientes'):
        if request.method == "GET":
            try:
                cliente = Cliente.objects.get(id=pk)
            except:
                return redirect("clientes:index")
            context={
                'nombre' : cliente.nombre,
                'direccion': cliente.direccion,
                'id': cliente.id,
            }
            return JsonResponse(context)
    return redirect("clientes:index")


@login_required(login_url="/")
def destroy(request,pk):
    if request.user.has_perm('clientes.delete_clientes'):
        if request.method == "GET":
            try:
                cliente = Cliente.objects.get(id=pk)
            except:
                return redirect("clientes:index")
            if request.user.empresa == cliente.empresa:
                try:
                    cliente.delete()
                except:
                    messages.success(request,f'No se puede eliminar elemento',extra_tags='danger')
    return redirect("clientes:index")


# @method_decorator(login_required, name='dispatch')
# class ListaSitiosCliente(ListView):
#     model = Sitios_cliente
#     template_name = 'clientes/sitios_list.html'

#     def get_context_data(self, **kwargs):
#         context = super(ListaSitiosCliente, self).get_context_data(**kwargs)
#         try:
#             cliente = Cliente.objects.get(id=self.kwargs['pk'])
#         except:
#             messages.success(self.request,f'Cliente no existe',extra_tags='danger')
#             return redirect("clientes:sitios", pk=self.kwargs['pk'])
#         context['appname'] = "sitios"
#         context['id_cliente'] = cliente.id
#         context['nombre_cliente'] = cliente.nombre
#         context['object_list'] = Sitios_cliente.objects.filter(empresa=self.request.user.empresa,cliente=cliente)
#         return context

#     def get_queryset(self):
#         queryset = Sitios_cliente.objects.filter(empresa=self.request.user.empresa)
#         return queryset
    
#     def get(self, request,pk):
#         if self.request.user.has_perm('clientes.view_sitios_cliente'):
#             return super().get(request)
#         return redirect("master:index")

# @method_decorator(login_required, name='dispatch')
# class CrearSitiosCliente(CreateView):
#     template_name = "clientes/formulario.html"
#     form_class = FormularioSitioCliente

#     def form_valid(self, form):
#         ruta = form.save(commit = False)
#         try:
#             cliente = Cliente.objects.get(id=self.kwargs['pk'])
#         except:
#             messages.success(self.request,f'Error al crear sitio',extra_tags='danger')
#             return redirect("clientes:sitios", pk=self.kwargs['pk'])
#         ruta.cliente = cliente
#         ruta.empresa = self.request.user.empresa
#         ruta.save()
#         return redirect("clientes:sitios", pk=self.kwargs['pk'])

#     def get_context_data(self, **kwargs):
#         context = super(CrearSitiosCliente, self).get_context_data(**kwargs)
#         try:
#             cliente = Cliente.objects.get(id=self.kwargs['pk'])
#         except:
#             messages.success(self.request,f'Error al crear sitio',extra_tags='danger')
#             return redirect("clientes:sitios", pk=self.kwargs['pk'])
#         context['legend'] = f"Agregar Sitio a {cliente.nombre.capitalize()}"
#         context['appname'] = "sitios"
#         return context

#     def get(self, request,pk):
#         if self.request.user.has_perm('clientes.add_sitios_cliente'):
#             return super().get(request)
#         return redirect("master:index")

# @method_decorator(login_required, name='dispatch')
# class EditarSitioCliente(UpdateView):
#     template_name = "clientes/formulario.html"
#     model = Sitios_cliente
#     form_class = FormularioSitioCliente

#     def form_valid(self,form):
#         form.save()
#         return redirect("clientes:sitios", pk=self.kwargs['pk'])

#     def get_context_data(self, **kwargs):
#         context = super(EditarSitioCliente, self).get_context_data(**kwargs)
#         context['legend'] = "Editar Sitio"
#         context['appname'] = "sitios"
#         return context

#     def get(self, request,pk):
#         objeto = self.get_object()
#         if self.request.user.empresa != objeto.empresa:
#             return redirect("master:index")
#         elif not self.request.user.has_perm('clientes.change_sitios_cliente'):
#             return redirect("clientes:sitios", pk=self.kwargs['pk'])
#         return super().get(request)

# @login_required(login_url="/")
# def predestroy_sitio(request, pk,pk_cliente):
#     if request.user.has_perm('clientes.delete_sitios_cliente'):
#         if request.method == "GET":
#             try:
#                 sitio = Sitios_cliente.objects.get(id=pk)
#             except:
#                 return redirect("clientes:sitios", pk=pk_cliente)
#             context={
#                 'nombre' : sitio.nombre,
#                 'direccion': sitio.direccion,
#                 'encargado': sitio.encargado,
#                 'id': sitio.id,
#             }
#             return JsonResponse(context)
#     return redirect("clientes:sitios", pk=pk_cliente)

# @login_required(login_url="/")
# def destroy_sitio(request, pk,pk_cliente):
#     if request.user.has_perm('clientes.delete_sitios_cliente'):
#         if request.method == "GET":
#             try:
#                 sitio = Sitios_cliente.objects.get(id=pk)
#             except:
#                 return redirect("clientes:sitios", pk=pk_cliente)
#             if request.user.empresa == sitio.empresa:
#                 try:
#                     sitio.delete()
#                 except:
#                     messages.success(request,f'No se puede eliminar elemento',extra_tags='danger')
#     return redirect("clientes:sitios", pk=pk_cliente)

templates/clientes/clientes_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    <div>
        <a href="{% url 'clientes:crear' %}" class="btn btn-success text-light border border-custom me-2"><i
                class="fas fa-plus-circle"></i> Agregar Cliente</a>
    </div>
</div>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Correo</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in object_list %}
            <tr>
                <td style="vertical-align: middle;">{{cliente.nombre}}</td>
                <td style="vertical-align: middle;">{{cliente.direccion}}</td>
                <td style="vertical-align: middle;">{{cliente.telefono}}</td>
                <td style="vertical-align: middle;">{{cliente.email}}</td>
                <td style="vertical-align: middle;">

                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'clientes:editar' pk=cliente.id %}" id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal" data-popup-url="{% url 'clientes:predestroy' pk=cliente.id %}"
                        href=""><i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar el siguiente cliente?:
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $(".dataTable").on('click', '.open-modal', function () {
            $.ajax({
                type: "GET",
                url: $(this).attr("data-popup-url"),
                dataType: "json",
                success: function (data) {
                    Datos =
                        "<p notempty='not'> Nombre: " + data['nombre'] +
                        "</p><p notempty='not'> Dirección: " + data['direccion'] +
                        "</p><p notempty='not' class='text-danger'> <strong>Si elimina este cliente se eliminaran todos los sitios asociados.</strong>" +
                        "</p>";
                    $(".modal-body").append(Datos);
                    $("#delete").click(function () {
                        window.location.href = "/clientes/destroy/" +
                            data["id"];
                    })
                }
            });
        });
        $("#close").on("click", function () {
            $(".modal-body").empty();
        })

        $('body').click(function (e) {
            if ($(e.target).attr('notempty') != "not")
                $(".modal-body").empty();
        });
    });
</script>
{% endblock javascript %}

templates/clientes/formulario.html
{% extends user.is_authenticated|yesno:"base.html,registration/base_login.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

{% if user.is_authenticated %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <button onclick="history.back()" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Atrás</button>
</div>
<div class="col-8 p-3 mx-auto border border-primary">
    <form enctype="multipart/form-data" class="text-dark" method="POST" class="rounded-3 text-white">
        {% else %}
        <form enctype="multipart/form-data" method="POST" class="rounded-3 text-white">
            {% endif %}
            <h2 class="text-center">{{legend}}</h2>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            {% crispy form %}
        </form>
</div>

{% endblock contenido %}

templates/clientes/sitios_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'clientes:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver atrás</a>
    <div>
        <h3>{{nombre_cliente}}</h3>
    </div>
    <div>
        <a href="{% url 'clientes:sitios_crear' pk=id_cliente %}"
            class="btn btn-success text-light border border-custom me-2"><i class="fas fa-plus-circle"></i> Agregar
            Sitio</a>
    </div>
</div>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<div class="table-responsive mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Correo</th>
                <th>Encargado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for sitio in object_list %}
            <tr>
                <td style="vertical-align: middle;">{{sitio.nombre}}</td>
                <td style="vertical-align: middle;">{{sitio.direccion}}</td>
                <td style="vertical-align: middle;">{{sitio.telefono}}</td>
                <td style="vertical-align: middle;">{{sitio.email}}</td>
                <td style="vertical-align: middle;">{{sitio.encargado}}</td>
                <td style="vertical-align: middle;">
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'clientes:sitios_editar' pk=sitio.id %}" id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal"
                        data-popup-url="{% url 'clientes:predestroy_sitio' pk=sitio.id pk_cliente=id_cliente %}"
                        href=""><i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar el siguiente Sitio?:
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $(".dataTable").on('click', '.open-modal', function () {
            $.ajax({
                type: "GET",
                url: $(this).attr("data-popup-url"),
                dataType: "json",
                success: function (data) {
                    Datos =
                        "<p notempty='not'> Nombre: " + data['nombre'] +
                        "</p><p notempty='not'> Dirección: " + data['direccion'] +
                        "</p><p notempty='not'> Encargado: " + data['encargado'] +
                        "</p>";
                    $(".modal-body").append(Datos);
                    $("#delete").click(function () {
                        window.location.href = "/clientes/sitios/destroy/" +
                            data["id"] + "/{{id_cliente}}"
                    })
                }
            });
        });
        $("#close").on("click", function () {
            $(".modal-body").empty();
        })

        $('body').click(function (e) {
            if ($(e.target).attr('notempty') != "not")
                $(".modal-body").empty();
        });
    });
</script>
{% endblock javascript %}